# Generated by Django 5.1.4 on 2024-12-30 04:41

import users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.MyUserManager()),
            ],
        ),
    ]
